#!/usr/bin/env dash
#
# This is the main algs4 Java environment setup script. It installs all
# dependencies required for working on algs4 problems.

dir=`dirname $0`
. "$dir"/step

base_dir=`realpath "$dir"/env`

# Manual downloads
jdk8_tar="jdk-8u131-linux-x64.tar.gz"
if test ! -f "$dir"/downloads/"$jdk8_tar" ; then
  printf '%s\n%s\n%s\n%s\n' "[MISSING FILE]: downloads/$jdk8_tar" "Please download Oracle Java SE Development Kit 8 (JDK) from" "\"http://www.oracle.com/technetwork/java/javase/downloads/index.html\"" "and move/rename the file to \"downloads/$jdk8_tar\"." 1>&2
  exit 1
fi

# Automatic downloads
step curl -so "$dir"/downloads/checkstyle-7.4-all.jar https://superb-dca2.dl.sourceforge.net/project/checkstyle/checkstyle/7.4/checkstyle-7.4-all.jar
step curl -so "$dir"/downloads/findbugs-3.0.1.tar.gz https://cytranet.dl.sourceforge.net/project/findbugs/findbugs/3.0.1/findbugs-3.0.1.tar.gz
step curl -so "$dir"/downloads/algs4.jar http://algs4.cs.princeton.edu/code/algs4.jar
step curl -so "$dir"/downloads/checkstyle-algs4.xml http://algs4.cs.princeton.edu/linux/checkstyle-coursera.xml
step curl -so "$dir"/downloads/findbugs-algs4.xml http://algs4.cs.princeton.edu/linux/findbugs-coursera.xml

# Verify downloads
step dash -c "cd $dir/downloads && sha1sum --check sha1sum.txt"
step dash -c "cd $dir/downloads && sha256sum --check sha256sum.txt"

# Extract JDK
step mkdir "$dir"/tmp
step tar -C "$dir"/tmp -xzf "$dir"/downloads/"$jdk8_tar"
step mkdir -p "$base_dir"
step mv "$dir"/tmp/* "$base_dir"/jdk
step rm -r "$dir"/tmp

# Create environment activation script
base_dir_pattern=`printf "$base_dir" | sed 's/\\//\\\\\\//g'`
step dash -c "sed 's/%VIRTUAL_ENV%/$base_dir_pattern/g' \"$base_dir\"/bin/activate.template 1>\"$base_dir\"/bin/activate"

# Add libraries
step mkdir -p "$base_dir"/lib
step cp "$dir"/downloads/algs4.jar "$base_dir"/lib

# Add tools
step mkdir -p "$base_dir"/config
step cp "$dir"/downloads/checkstyle-algs4.xml "$base_dir"/config
step cp "$dir"/downloads/findbugs-algs4.xml "$base_dir"/config
step mkdir -p "$base_dir"/tools
step cp "$dir"/downloads/checkstyle-7.4-all.jar "$base_dir"/tools
step mkdir "$dir"/tmp
step tar -C "$dir"/tmp -xzf "$dir"/downloads/findbugs-3.0.1.tar.gz
step mv "$dir"/tmp/* "$base_dir"/tools/findbugs
step rm -r "$dir"/tmp

