#!/usr/bin/env dash
#
# This is the main algs4 Java environment setup script. It installs all
# dependencies required for working on algs4 problems.

dir=`dirname $0`
. "$dir"/step

base_dir="~/env/algs4"

# Manual downloads
jdk8_tar="jdk-8uXXX-linux-x64.tar.gz"
if test ! -f "$dir"/downloads/"$jdk8_tar" ; then
  printf '%s\n%s\n%s\n%s\n' "[MISSING FILE]: downloads/$jdk8_tar" "Please download the latest Oracle Java SE 8 JDK from" "\"http://www.oracle.com/technetwork/java/javase/downloads/index.html\"" "and move/rename the file to \"downloads/$jdk8_tar\"." 1>&2
  exit 1
fi

# Automatic downloads
step curl -so "$dir"/downloads/checkstyle-7.4-all.jar https://superb-dca2.dl.sourceforge.net/project/checkstyle/checkstyle/7.4/checkstyle-7.4-all.jar
step curl -so "$dir"/downloads/algs4.jar http://algs4.cs.princeton.edu/code/algs4.jar

# Verify downloads
step dash -c "cd $dir/downloads && sha1sum --check sha1sum.txt"

# Extract JDK
step mkdir "$dir"/jdk
step tar -C "$dir"/jdk -xzf "$dir"/downloads/"$jdk8_tar"
step mkdir -p "$base_dir"
step mv "$dir"/jdk/* "$base_dir"/jdk
step rm -r "$dir"/jdk

# Add libraries
step mkdir "$base_dir"/lib
step cp "$dir"/downloads/algs4.jar "$base_dir"/lib

